---
version: 1
ansible_config: ansible.cfg
build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/aap/ansible-automation-platform-20-ee-minimal-rhel8:latest'
  EE_BUILDER_IMAGE: 'quay.io/aap/ansible-automation-platform-20-ee-builder-rhel8:latest'
dependencies:
  galaxy: requirements.yml
